#pragma once
/* Browser UI for AlisBoard.exe — USB only, no Wi-Fi. Open http://127.0.0.1:48123 */
static const char WEBUI_WIN_HTML[] =
"<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"utf-8\"/>"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"/>"
"<title>AlisBoard</title><link rel=\"icon\" href=\"/favicon.ico\" type=\"image/x-icon\"/><style>"
":root{--bg:#0f172a;--card:#1e293b;--line:#334155;--t:#e2e8f0;--m:#94a3b8;--ok:#34d399;--bad:#f87171;--acc:#2dd4bf}"
"*{box-sizing:border-box}body{margin:0;font-family:Segoe UI,Tahoma,sans-serif;background:var(--bg);color:var(--t)}"
"header{padding:16px 20px;border-bottom:1px solid var(--line)}"
"h1{margin:0;font-size:20px}h2{margin:0 0 10px;font-size:13px;color:var(--m);text-transform:uppercase;letter-spacing:.04em}"
".wrap{max-width:880px;margin:0 auto;padding:16px 20px 40px}"
".card{background:var(--card);border:1px solid var(--line);border-radius:10px;padding:14px 16px;margin:0 0 12px}"
".row{display:flex;justify-content:space-between;gap:10px;padding:4px 0;font-size:14px}"
".status-row{padding:7px 0;font-size:14px;border-bottom:1px solid var(--line)}"
".status-row:last-of-type{border-bottom:0}"
".status-row .k{display:block;color:var(--m);font-size:12px;margin-bottom:3px}"
".status-row .v{display:block;text-align:left;direction:ltr;word-break:break-word;line-height:1.4}"
".k{color:var(--m)}.ok{color:var(--ok)}.bad{color:var(--bad)}.note{text-align:left;direction:ltr;color:var(--acc);font-size:13px;margin:10px 0 0;line-height:1.45}"
"label{display:block;color:var(--m);font-size:12px;margin:8px 0 4px}"
"input{width:100%;padding:8px 10px;border-radius:8px;border:1px solid var(--line);background:#0f172a;color:var(--t)}"
"button{margin:8px 8px 0 0;padding:8px 14px;border-radius:8px;border:0;background:var(--acc);color:#042f2e;font-weight:700;cursor:pointer}"
"button.ghost{background:#0f172a;color:var(--t);border:1px solid var(--line)}"
".log-head{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:8px}"
".log-head h2{margin:0}"
".logbox{display:block;white-space:pre-wrap;word-break:break-word;font:12px/1.45 Consolas,monospace;height:300px;overflow-y:scroll;overflow-x:auto;padding:10px 12px;border:1px solid var(--line);border-radius:8px;background:#0b1220;color:var(--t);user-select:text;-webkit-user-select:text}"
"</style></head><body>"
"<header><h1>AlisBoard</h1><div class=\"k\" id=\"sub\">USB - no Wi-Fi needed for this page</div></header>"
"<div class=\"wrap\">"
"<div class=\"card\"><h2>Status</h2>"
"<div class=\"status-row\"><span class=\"k\">Windows user</span><span class=\"v\" id=\"s_user\"></span></div>"
"<div class=\"status-row\"><span class=\"k\">USB folder</span><span class=\"v\" id=\"s_folder\"></span></div>"
"<div class=\"status-row\"><span class=\"k\">SQL Server</span><span class=\"v\" id=\"s_sql\"></span></div>"
"<div class=\"status-row\"><span class=\"k\">ESP32-S3</span><span class=\"v\" id=\"s_esp\"></span></div>"
"<div class=\"status-row\"><span class=\"k\">ESP API URL (board POSTs here)</span><span class=\"v\" id=\"s_esp_api\"></span></div>"
"<p class=\"note\">This page runs on the PC from AlisBoard.exe on the USB disk. Settings go to IN.JSON on drive G:.</p>"
"</div>"
"<div class=\"card\"><h2>SQL Server</h2>"
"<label>Server / Instance</label><input id=\"sql_server\"/>"
"<label>Database (all = every user DB, oldest first then live)</label><input id=\"sql_db\"/>"
"<label>Authentication</label><input value=\"Windows Authentication\" disabled/>"
"<button onclick=\"saveSql()\">Save SQL</button>"
"<button class=\"ghost\" onclick=\"testSql()\">Test SQL</button>"
"<p class=\"note\">Copies every table (except huge binary columns) to the mill API as JSON. Same body ESP would POST.</p>"
"</div>"
"<div class=\"card\"><h2>Mill API — same JSON as ESP32-S3</h2>"
"<label>Wi-Fi SSID (only if ESP should POST too)</label><input id=\"wifi_ssid\"/>"
"<label>Wi-Fi password</label><input id=\"wifi_pass\" type=\"password\"/>"
"<label>API URL (PC and ESP use this)</label><input id=\"api_url\"/>"
"<label>Token</label><input id=\"api_token\" type=\"password\"/>"
"<button onclick=\"sendEsp()\">Send to ESP (IN.JSON)</button>"
"<p class=\"note\">Leave SSID empty: this PC POSTs. Fill SSID: ESP POSTs the same sql_sync JSON over Wi-Fi.</p>"
"</div>"
"<div class=\"card\"><div class=\"log-head\"><h2>Logs</h2><button class=\"ghost\" onclick=\"copyLogs()\">Copy logs</button></div>"
"<div class=\"logbox\" id=\"logs\">loading...</div></div>"
"</div><script>"
"async function j(u,o){const r=await fetch(u,o);return r.json()}"
"function setLogs(t){var el=document.getElementById('logs');var stick=el.scrollTop+el.clientHeight>=el.scrollHeight-12;el.textContent=t||'';if(stick)el.scrollTop=el.scrollHeight;}"
"function copyLogs(){var t=document.getElementById('logs').textContent||'';if(window.clipboard&&window.clipboard.writeText){window.clipboard.writeText(t);return;}"
"var ta=document.createElement('textarea');ta.value=t;document.body.appendChild(ta);ta.select();try{document.execCommand('copy');}catch(e){}document.body.removeChild(ta);}"
"function paint(s){"
"document.getElementById('s_user').textContent=s.windows_user||'-';"
"document.getElementById('s_folder').textContent=s.usb_folder||'-';"
"document.getElementById('s_sql').className=s.sql_connected?'ok':'bad';"
"document.getElementById('s_sql').textContent=s.sql_status||'-';"
"document.getElementById('s_esp').textContent=s.esp_status||'-';"
"document.getElementById('s_esp_api').textContent=s.esp_api_url||s.api_url||'-';"
"if(document.activeElement!==document.getElementById('sql_server')) document.getElementById('sql_server').value=s.server||'';"
"if(document.activeElement!==document.getElementById('sql_db')) document.getElementById('sql_db').value=s.database||'';"
"if(document.activeElement!==document.getElementById('wifi_ssid')) document.getElementById('wifi_ssid').value=s.wifi_ssid||'';"
"if(document.activeElement!==document.getElementById('api_url')) document.getElementById('api_url').value=s.api_url||'';"
"setLogs(s.logs||'');"
"}"
"async function tick(){try{paint(await j('/api/status'))}catch(e){setLogs(String(e))}}"
"async function saveSql(){await j('/api/sql',{method:'POST',headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({server:sql_server.value,database:sql_db.value})});tick()}"
"async function testSql(){const r=await j('/api/test-sql',{method:'POST'});alert(JSON.stringify(r,null,2));tick()}"
"async function sendEsp(){await j('/api/esp',{method:'POST',headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({ssid:wifi_ssid.value,password:wifi_pass.value,api_url:api_url.value,api_token:api_token.value})});tick()}"
"tick();setInterval(tick,3000);"
"</script></body></html>";
